image: lorisleiva/laravel-docker:stable

variables:
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: "nuke"
  DB_USERNAME: "nuke"
  DB_PASSWORD: "$NUKE_DB_PASSWORD"

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;


# Just build, pre-deploy, and deploy for now. 
# Can add 'test' later if testing gets added
stages:
  - build
  - pre-deploy
  - deploy


#######################################
#            Build Stage              #
#######################################
composer:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vender/
  script:
    - echo "https://mirror.csclub.uwaterloo.ca/alpine/latest-stable/main" > /etc/apk/repositories
    - echo "https://mirror.csclub.uwaterloo.ca/alpine/latest-stable/community" >>/etc/apk/repositories
    - apk add --no-cache php-dev
    - pecl install redis
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.gitlab-ci .env
    - php artisan key:generate
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env

npm:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run production
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/
      - public/mix-manifest.json


#######################################
#          Pre-Deploy Stage           #
#######################################

#### NOT USED YET

#######################################
#            Deploy Stage             #
#######################################

staging:
  variables:
    DB_HOST: "d2.jhvisser.com"
    DB_USERNAME: "nuke"
    DB_DATABASE: "nuke-stage"
    APP_ENV: "staging"
    APP_DEBUG: "true"
    APP_URL: "https://nuke-stage.jhvisser.com"
    CI_DEBUG_TRACE: "true"
  stage: deploy
  script:
    - *init_ssh
    - *change_file_permissions
    - php artisan config:cache
    - php artisan deploy nuke-stage.jhvisser.com -s upload
  environment:
    name: staging
    url: https://nuke-stage.jhvisser.com
  only:
    - laravel

production:
  variables:
    DB_HOST: "d2.jhvisser.com"
    DB_USERNAME: "nuke"
    DB_DATABASE: "nuke"
    APP_ENV: "production"
    APP_DEBUG: "false"
    APP_URL: "https://nuke.jhvisser.com"
  stage: deploy
  script:
    - *init_ssh
    - *change_file_permissions
    - php artisan config:cache
    - php artisan deploy nuke.jhvisser.com -s upload
  environment:
    name: staging
    url: https://nuke.jhvisser.com
  when: manual
  only:
    - laravel

